package com.othon.carvalho.repository.app;
import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.query.Param;

import com.othon.carvalho.model.app.Produto;

public interface Repositoryo extends CrudRepository<Produto, Integer>{
    @Query(value = "select  t.codprod, t.descricao, t.unidade,t.codauxiliar,r.pvenda1 as precoatual,(SELECT TO_CHAR(MAX(PCPRECO.dataalter),'DD-MM-YYYY') FROM OTHON.PCPRECO WHERE CODPROD = T.CODPROD AND PVENDAANT <> PVENDA) AS DTALTERACAOPRECO, (SELECT MAX(Y.pvendaant)  FROM OTHON.pcpreco Y WHERE Y.CODPROD = T.CODPROD AND Y.dataalter = (SELECT MAX(DATAALTER) FROM OTHON.PCPRECO WHERE CODPROD = T.CODPROD AND PVENDA <> PVENDAANT)) AS PRECOANTERIOR,(select max(m.precofixo) from  othon.pcprecoprom m where t.codprod = m.codprod and m.dtfimvigencia > sysdate  and numregiao in (1))as precopromocional, (select max(m.dtfimvigencia) from othon.pcprecoprom m where t.codprod = m.codprod and m.dtfimvigencia > sysdate and numregiao in (1) )as Fimvigencia, (select codprod || '-' || descricao from othon.pcprodut where codprod = t.codprodprinc) as produtopai, (select qtestger from othon.pcest where codfilial = 3 and codprod = t.codprod ) as estoqueCD, e.qtestger as estoqueOthon, (e.qtestger - e.qtreserv - e.qtbloqueada ) as estoquedispOthon, (SELECT ROUND(SYSDATE - MAX(DTMOV)) FROM OTHON.PCMOV WHERE CODPROD = T.CODPROD AND CODOPER = 'S' AND CODFILIAL = 1 AND DTCANCEL IS NULL ) AS QTDIASSEMVENDA, (select sum(qtpedida - qtentregue) from OTHON.pcitem where codprod = t.codprod and qtentregue < qtpedida and dataentrega > '01-jan-2021'  group by codprod) as qtachegar, sum(g.giro) as giromes, (select sum(qt) from othon.pcmov where CODPROD = T.CODPROD  AND codoper = 'S' AND CODFILIAL IN (1,4) AND DTCANCEL IS NULL  AND NUMNOTA IN (SELECT NUMNOTA FROM othon.PCNFSAID WHERE DTCANCEL IS NULL) AND DTMOV > SYSDATE - 90 GROUP BY CODPROD) AS QTVENDIDA3MESES  from  othon.pctabpr r ,  othon.pcprodut t, othon.pcest e , othon.pcgiro g where   t.codprod = r.codprod and r.numregiao = 9 and t.codprod = e.codprod and e.codfilial = 1 and g.codprod(+) = t.codprod and g.codfilial(+) = 1 AND T.codprod = ?1  group by t.codprod, t.descricao, t.unidade, e.qtestger, t.codprodprinc, e.qtreserv, e.qtbloqueada,r.pvenda1,t.codauxiliar", nativeQuery = true)
    Optional<Produto> findAll(String codigo);
    @Query(value = "select  t.codprod, t.descricao, t.unidade,t.codauxiliar,r.pvenda1 as precoatual,(SELECT TO_CHAR(MAX(PCPRECO.dataalter),'DD-MM-YYYY') FROM OTHON.PCPRECO WHERE CODPROD = T.CODPROD AND PVENDAANT <> PVENDA) AS DTALTERACAOPRECO, (SELECT MAX(Y.pvendaant)  FROM OTHON.pcpreco Y WHERE Y.CODPROD = T.CODPROD AND Y.dataalter = (SELECT MAX(DATAALTER) FROM OTHON.PCPRECO WHERE CODPROD = T.CODPROD AND PVENDA <> PVENDAANT)) AS PRECOANTERIOR,(select max(m.precofixo) from  othon.pcprecoprom m where t.codprod = m.codprod and m.dtfimvigencia > sysdate  and numregiao in (1))as precopromocional, (select max(m.dtfimvigencia) from othon.pcprecoprom m where t.codprod = m.codprod and m.dtfimvigencia > sysdate and numregiao in (1) )as Fimvigencia, (select codprod || '-' || descricao from othon.pcprodut where codprod = t.codprodprinc) as produtopai, (select qtestger from othon.pcest where codfilial = 3 and codprod = t.codprod ) as estoqueCD, e.qtestger as estoqueOthon, (e.qtestger - e.qtreserv - e.qtbloqueada ) as estoquedispOthon, (SELECT ROUND(SYSDATE - MAX(DTMOV)) FROM OTHON.PCMOV WHERE CODPROD = T.CODPROD AND CODOPER = 'S' AND CODFILIAL = 1 AND DTCANCEL IS NULL ) AS QTDIASSEMVENDA, (select sum(qtpedida - qtentregue) from OTHON.pcitem where codprod = t.codprod and qtentregue < qtpedida and dataentrega > '01-jan-2021'  group by codprod) as qtachegar, sum(g.giro) as giromes, (select sum(qt) from othon.pcmov where CODPROD = T.CODPROD  AND codoper = 'S' AND CODFILIAL IN (1,4) AND DTCANCEL IS NULL  AND NUMNOTA IN (SELECT NUMNOTA FROM othon.PCNFSAID WHERE DTCANCEL IS NULL) AND DTMOV > SYSDATE - 90 GROUP BY CODPROD) AS QTVENDIDA3MESES  from  othon.pctabpr r ,  othon.pcprodut t, othon.pcest e , othon.pcgiro g where   t.codprod = r.codprod and r.numregiao = 9 and t.codprod = e.codprod and e.codfilial = 1 and g.codprod(+) = t.codprod and g.codfilial(+) = 1 AND T.codauxiliar = ?1  group by t.codprod, t.descricao, t.unidade, e.qtestger, t.codprodprinc, e.qtreserv, e.qtbloqueada,r.pvenda1,t.codauxiliar ", nativeQuery = true)
    Optional<Produto> find(String codigo);
}
